### ISSUE TITLE
Issue with required package FixedEffectModels.jl

### ISSUE THREAD

**Issue by chriscandelaria** [matthieugomez/SparseFactorModels.jl#2]
I recently updated to the latest version of SparseFactorModels.jl on the master branch  using Pkg.checkout("SparseFactorModels"), but I am getting the following error: 

```
julia> Pkg.checkout("SparseFactorModels")
INFO: Checking out SparseFactorModels master...
INFO: Pulling SparseFactorModels latest master...
WARNING: FixedEffectModels is fixed at 0.1.0+ conflicting with requirement for SparseFactorModels: [0.1.1,∞)
```

I also updated to the latest FixedEffectModels.jl program, but I get the following after typing Pkg.status():

```
 - FixedEffectModels             0.1.0+             master
```

It appears that SparseFactorModels is requesting a version of FixedEffectModels that is not available.

**Comment by matthieugomez** [comment]
Use `Pkg.update()` to update all your packages (including FixedEffectModels)

**Comment by chriscandelaria** [comment]
Thanks. I am relatively new to Git and Github. I assumed that Pkg.checkout("FixedEffectModels") would give me the latest version of the program on the master branch. I was wrong. Thanks for the Pkg.update() suggestion.

**Comment by matthieugomez** [comment]
I thought too. Not sure why this happened.
